// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimInvite = `-- name: ClaimInvite :one
UPDATE invites SET used_at = now()
WHERE code_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id
`

// Занимает инвайт; вызывать в транзакции вместе с созданием пользователя.
func (q *Queries) ClaimInvite(ctx context.Context, codeHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimInvite, codeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code_hash, created_by, expires_at)
VALUES ($1, $2, $3)
RETURNING id, created_at, expires_at
`

type CreateInviteParams struct {
	CodeHash  []byte
	CreatedBy uuid.UUID
	ExpiresAt time.Time
}

type CreateInviteRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.CodeHash, arg.CreatedBy, arg.ExpiresAt)
	var i CreateInviteRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, display_name, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, login, display_name, password_hash, is_admin, created_at
`

type CreateUserParams struct {
	Login        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Login,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const deleteUnusedInvite = `-- name: DeleteUnusedInvite :execrows
DELETE FROM invites WHERE id = $1 AND used_at IS NULL
`

// Использованные инвайты не удаляются: они — история, кто кого пригласил.
func (q *Queries) DeleteUnusedInvite(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const extendSession = `-- name: ExtendSession :exec
UPDATE sessions SET expires_at = $2 WHERE token_hash = $1
`

type ExtendSessionParams struct {
	TokenHash []byte
	ExpiresAt time.Time
}

func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) error {
	_, err := q.db.Exec(ctx, extendSession, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.login, users.display_name, users.password_hash, users.is_admin, users.created_at, sessions.expires_at AS session_expires_at
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1 AND sessions.expires_at > now()
`

type GetSessionUserRow struct {
	User             User
	SessionExpiresAt time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Login,
		&i.User.DisplayName,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.SessionExpiresAt,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, display_name, password_hash, is_admin, created_at FROM users WHERE lower(login) = lower($1)
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT i.id, i.created_at, i.expires_at, i.used_at, u.login AS used_by_login
FROM invites i
LEFT JOIN users u ON u.id = i.used_by
ORDER BY i.created_at DESC
`

type ListInvitesRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UsedAt      *time.Time
	UsedByLogin *string
}

func (q *Queries) ListInvites(ctx context.Context) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitesRow
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedByLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setInviteUser = `-- name: SetInviteUser :exec
UPDATE invites SET used_by = $2 WHERE id = $1
`

type SetInviteUserParams struct {
	ID     uuid.UUID
	UsedBy *uuid.UUID
}

func (q *Queries) SetInviteUser(ctx context.Context, arg SetInviteUserParams) error {
	_, err := q.db.Exec(ctx, setInviteUser, arg.ID, arg.UsedBy)
	return err
}
