// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const claimInvite = `-- name: ClaimInvite :one
UPDATE invites SET used_at = now()
WHERE code_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING id
`

// Вызывать в одной транзакции с CreateUser.
func (q *Queries) ClaimInvite(ctx context.Context, codeHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimInvite, codeHash)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const confirmSession = `-- name: ConfirmSession :exec
UPDATE sessions SET confirmed_at = now() WHERE id = $1 AND confirmed_at IS NULL
`

func (q *Queries) ConfirmSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, confirmSession, id)
	return err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (code_hash, created_by, expires_at)
VALUES ($1, $2, $3)
RETURNING id, created_at, expires_at
`

type CreateInviteParams struct {
	CodeHash  []byte
	CreatedBy uuid.UUID
	ExpiresAt time.Time
}

type CreateInviteRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite, arg.CodeHash, arg.CreatedBy, arg.ExpiresAt)
	var i CreateInviteRow
	err := row.Scan(&i.ID, &i.CreatedAt, &i.ExpiresAt)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at, user_agent)
VALUES ($1, $2, $3, $4)
`

type CreateSessionParams struct {
	TokenHash []byte
	UserID    uuid.UUID
	ExpiresAt time.Time
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, display_name, password_hash, is_admin)
VALUES ($1, $2, $3, $4)
RETURNING id, login, display_name, password_hash, is_admin, created_at, avatar_sha256, character_seq
`

type CreateUserParams struct {
	Login        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Login,
		arg.DisplayName,
		arg.PasswordHash,
		arg.IsAdmin,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.AvatarSha256,
		&i.CharacterSeq,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOtherSessions = `-- name: DeleteOtherSessions :execrows
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteOtherSessionsParams struct {
	UserID uuid.UUID
	KeepID uuid.UUID
}

func (q *Queries) DeleteOtherSessions(ctx context.Context, arg DeleteOtherSessionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOtherSessions, arg.UserID, arg.KeepID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const deleteUnusedInvite = `-- name: DeleteUnusedInvite :execrows
DELETE FROM invites WHERE id = $1 AND used_at IS NULL
`

// Использованные остаются как история.
func (q *Queries) DeleteUnusedInvite(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedInvite, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSession = `-- name: DeleteUserSession :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteUserSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteUserSession(ctx context.Context, arg DeleteUserSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findSession = `-- name: FindSession :one
SELECT users.id, users.login, users.display_name, users.password_hash, users.is_admin, users.created_at, users.avatar_sha256, users.character_seq,
       sessions.id AS session_id,
       sessions.created_at AS session_created_at,
       sessions.expires_at AS session_expires_at,
       sessions.rotated_at,
       sessions.confirmed_at,
       sessions.last_used_at,
       sessions.token_hash = $1 AS is_current
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE (sessions.token_hash = $1 OR sessions.prev_token_hash = $1)
  AND sessions.expires_at > now() AND sessions.created_at > $2
`

type FindSessionParams struct {
	TokenHash    []byte
	CreatedAfter time.Time
}

type FindSessionRow struct {
	User             User
	SessionID        uuid.UUID
	SessionCreatedAt time.Time
	SessionExpiresAt time.Time
	RotatedAt        time.Time
	ConfirmedAt      *time.Time
	LastUsedAt       time.Time
	IsCurrent        bool
}

func (q *Queries) FindSession(ctx context.Context, arg FindSessionParams) (FindSessionRow, error) {
	row := q.db.QueryRow(ctx, findSession, arg.TokenHash, arg.CreatedAfter)
	var i FindSessionRow
	err := row.Scan(
		&i.User.ID,
		&i.User.Login,
		&i.User.DisplayName,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.CreatedAt,
		&i.User.AvatarSha256,
		&i.User.CharacterSeq,
		&i.SessionID,
		&i.SessionCreatedAt,
		&i.SessionExpiresAt,
		&i.RotatedAt,
		&i.ConfirmedAt,
		&i.LastUsedAt,
		&i.IsCurrent,
	)
	return i, err
}

const getUserByLogin = `-- name: GetUserByLogin :one
SELECT id, login, display_name, password_hash, is_admin, created_at, avatar_sha256, character_seq FROM users WHERE lower(login) = lower($1)
`

func (q *Queries) GetUserByLogin(ctx context.Context, login string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByLogin, login)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.AvatarSha256,
		&i.CharacterSeq,
	)
	return i, err
}

const listInvites = `-- name: ListInvites :many
SELECT i.id, i.created_at, i.expires_at, i.used_at, u.login AS used_by_login
FROM invites i
LEFT JOIN users u ON u.id = i.used_by
ORDER BY i.created_at DESC
`

type ListInvitesRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	ExpiresAt   time.Time
	UsedAt      *time.Time
	UsedByLogin *string
}

func (q *Queries) ListInvites(ctx context.Context) ([]ListInvitesRow, error) {
	rows, err := q.db.Query(ctx, listInvites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInvitesRow
	for rows.Next() {
		var i ListInvitesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedByLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, created_at, last_used_at, user_agent
FROM sessions
WHERE user_id = $1 AND expires_at > now() AND created_at > $2
ORDER BY last_used_at DESC
`

type ListUserSessionsParams struct {
	UserID       uuid.UUID
	CreatedAfter time.Time
}

type ListUserSessionsRow struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	LastUsedAt time.Time
	UserAgent  string
}

func (q *Queries) ListUserSessions(ctx context.Context, arg ListUserSessionsParams) ([]ListUserSessionsRow, error) {
	rows, err := q.db.Query(ctx, listUserSessions, arg.UserID, arg.CreatedAfter)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserSessionsRow
	for rows.Next() {
		var i ListUserSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.UserAgent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reissueSession = `-- name: ReissueSession :execrows
UPDATE sessions SET token_hash = $1, rotated_at = now()
WHERE id = $2 AND prev_token_hash = $3 AND confirmed_at IS NULL AND rotated_at < $4
`

type ReissueSessionParams struct {
	NewHash       []byte
	ID            uuid.UUID
	PrevHash      []byte
	ReissueBefore time.Time
}

// Ответ с новым токеном потерялся: клиент пришёл со старым — выдаём ещё один.
func (q *Queries) ReissueSession(ctx context.Context, arg ReissueSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, reissueSession,
		arg.NewHash,
		arg.ID,
		arg.PrevHash,
		arg.ReissueBefore,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rotateSession = `-- name: RotateSession :execrows
UPDATE sessions
SET prev_token_hash = token_hash, token_hash = $1, rotated_at = now(), confirmed_at = NULL
WHERE id = $2 AND token_hash = $3
`

type RotateSessionParams struct {
	NewHash     []byte
	ID          uuid.UUID
	CurrentHash []byte
}

// Условие на token_hash: из параллельных запросов ротирует один.
func (q *Queries) RotateSession(ctx context.Context, arg RotateSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateSession, arg.NewHash, arg.ID, arg.CurrentHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInviteUser = `-- name: SetInviteUser :exec
UPDATE invites SET used_by = $2 WHERE id = $1
`

type SetInviteUserParams struct {
	ID     uuid.UUID
	UsedBy *uuid.UUID
}

func (q *Queries) SetInviteUser(ctx context.Context, arg SetInviteUserParams) error {
	_, err := q.db.Exec(ctx, setInviteUser, arg.ID, arg.UsedBy)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_used_at = now(), expires_at = $1 WHERE id = $2
`

type TouchSessionParams struct {
	ExpiresAt time.Time
	ID        uuid.UUID
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ExpiresAt, arg.ID)
	return err
}

const updateUserLogin = `-- name: UpdateUserLogin :one
UPDATE users SET login = $1 WHERE id = $2
RETURNING id, login, display_name, password_hash, is_admin, created_at, avatar_sha256, character_seq
`

type UpdateUserLoginParams struct {
	Login string
	ID    uuid.UUID
}

func (q *Queries) UpdateUserLogin(ctx context.Context, arg UpdateUserLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserLogin, arg.Login, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.AvatarSha256,
		&i.CharacterSeq,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users SET password_hash = $1 WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string
	ID           uuid.UUID
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}
