// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blobs.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const deleteUnusedBlobs = `-- name: DeleteUnusedBlobs :execrows
DELETE FROM blobs b
WHERE b.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_sha256 = b.sha256)
`

// Каждая таблица со ссылкой на blobs — здесь (D63).
func (q *Queries) DeleteUnusedBlobs(ctx context.Context, before time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUnusedBlobs, before)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBlob = `-- name: GetBlob :one
SELECT mime, bytes FROM blobs WHERE sha256 = $1
`

type GetBlobRow struct {
	Mime  string
	Bytes []byte
}

func (q *Queries) GetBlob(ctx context.Context, sha256 []byte) (GetBlobRow, error) {
	row := q.db.QueryRow(ctx, getBlob, sha256)
	var i GetBlobRow
	err := row.Scan(&i.Mime, &i.Bytes)
	return i, err
}

const putBlob = `-- name: PutBlob :exec
INSERT INTO blobs (sha256, mime, bytes)
VALUES ($1, $2, $3)
ON CONFLICT (sha256) DO UPDATE SET created_at = now()
`

type PutBlobParams struct {
	Sha256 []byte
	Mime   string
	Bytes  []byte
}

// Повторная загрузка заново отсчитывает срок до очистки.
func (q *Queries) PutBlob(ctx context.Context, arg PutBlobParams) error {
	_, err := q.db.Exec(ctx, putBlob, arg.Sha256, arg.Mime, arg.Bytes)
	return err
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE users SET avatar_sha256 = $1 WHERE id = $2
RETURNING id, login, display_name, password_hash, is_admin, created_at, avatar_sha256, character_seq
`

type SetUserAvatarParams struct {
	AvatarSha256 []byte
	ID           uuid.UUID
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserAvatar, arg.AvatarSha256, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.DisplayName,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.AvatarSha256,
		&i.CharacterSeq,
	)
	return i, err
}
