// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: characters.sql

package dbq

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getCharacter = `-- name: GetCharacter :one
SELECT id, owner_id, revision, seq, data, updated_at FROM characters WHERE id = $1
`

func (q *Queries) GetCharacter(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacter, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Revision,
		&i.Seq,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterForUpdate = `-- name: GetCharacterForUpdate :one
SELECT id, owner_id, revision, seq, data, updated_at FROM characters WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetCharacterForUpdate(ctx context.Context, id uuid.UUID) (Character, error) {
	row := q.db.QueryRow(ctx, getCharacterForUpdate, id)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Revision,
		&i.Seq,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const getCharacterSeq = `-- name: GetCharacterSeq :one
SELECT character_seq FROM users WHERE id = $1
`

func (q *Queries) GetCharacterSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getCharacterSeq, id)
	var character_seq int64
	err := row.Scan(&character_seq)
	return character_seq, err
}

const insertCharacter = `-- name: InsertCharacter :one
INSERT INTO characters (id, owner_id, revision, seq, data)
VALUES ($1, $2, 1, $3, $4)
RETURNING id, owner_id, revision, seq, data, updated_at
`

type InsertCharacterParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Seq     int64
	Data    []byte
}

func (q *Queries) InsertCharacter(ctx context.Context, arg InsertCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, insertCharacter,
		arg.ID,
		arg.OwnerID,
		arg.Seq,
		arg.Data,
	)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Revision,
		&i.Seq,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}

const listCharacterChanges = `-- name: ListCharacterChanges :many
SELECT id, owner_id, revision, seq, data, updated_at FROM characters
WHERE owner_id = $1 AND seq > $2 AND seq <= $3 AND ($2::bigint > 0 OR data IS NOT NULL)
ORDER BY seq
`

type ListCharacterChangesParams struct {
	OwnerID uuid.UUID
	Since   int64
	Until   int64
}

// Первая загрузка (since = 0) — без надгробий: удалённое клиенту не нужно.
func (q *Queries) ListCharacterChanges(ctx context.Context, arg ListCharacterChangesParams) ([]Character, error) {
	rows, err := q.db.Query(ctx, listCharacterChanges, arg.OwnerID, arg.Since, arg.Until)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Character
	for rows.Next() {
		var i Character
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Revision,
			&i.Seq,
			&i.Data,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCharacterSeq = `-- name: NextCharacterSeq :one
UPDATE users SET character_seq = character_seq + 1 WHERE id = $1
RETURNING character_seq
`

// Блокирует пользователя до конца транзакции: изменения его анкет идут по одному,
// поэтому seq растёт в порядке коммитов и курсор не перескочит незакоммиченное.
func (q *Queries) NextCharacterSeq(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextCharacterSeq, id)
	var character_seq int64
	err := row.Scan(&character_seq)
	return character_seq, err
}

const saveCharacterRevision = `-- name: SaveCharacterRevision :exec
INSERT INTO character_revisions (character_id, revision, data, updated_at)
VALUES ($1, $2, $3, $4)
`

type SaveCharacterRevisionParams struct {
	CharacterID uuid.UUID
	Revision    int64
	Data        []byte
	UpdatedAt   time.Time
}

func (q *Queries) SaveCharacterRevision(ctx context.Context, arg SaveCharacterRevisionParams) error {
	_, err := q.db.Exec(ctx, saveCharacterRevision,
		arg.CharacterID,
		arg.Revision,
		arg.Data,
		arg.UpdatedAt,
	)
	return err
}

const trimCharacterRevisions = `-- name: TrimCharacterRevisions :exec
DELETE FROM character_revisions WHERE character_id = $1 AND revision <= $2
`

type TrimCharacterRevisionsParams struct {
	CharacterID uuid.UUID
	UpTo        int64
}

func (q *Queries) TrimCharacterRevisions(ctx context.Context, arg TrimCharacterRevisionsParams) error {
	_, err := q.db.Exec(ctx, trimCharacterRevisions, arg.CharacterID, arg.UpTo)
	return err
}

const updateCharacter = `-- name: UpdateCharacter :one
UPDATE characters SET revision = revision + 1, seq = $1, data = $2, updated_at = now()
WHERE id = $3
RETURNING id, owner_id, revision, seq, data, updated_at
`

type UpdateCharacterParams struct {
	Seq  int64
	Data []byte
	ID   uuid.UUID
}

// data NULL — удаление.
func (q *Queries) UpdateCharacter(ctx context.Context, arg UpdateCharacterParams) (Character, error) {
	row := q.db.QueryRow(ctx, updateCharacter, arg.Seq, arg.Data, arg.ID)
	var i Character
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Revision,
		&i.Seq,
		&i.Data,
		&i.UpdatedAt,
	)
	return i, err
}
