// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbq

import (
	"time"

	"github.com/google/uuid"
)

type Blob struct {
	Sha256    []byte
	Mime      string
	Bytes     []byte
	CreatedAt time.Time
}

type Invite struct {
	ID        uuid.UUID
	CodeHash  []byte
	CreatedBy uuid.UUID
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
	UsedBy    *uuid.UUID
}

type Session struct {
	TokenHash     []byte
	UserID        uuid.UUID
	CreatedAt     time.Time
	ExpiresAt     time.Time
	UserAgent     string
	ID            uuid.UUID
	PrevTokenHash []byte
	RotatedAt     time.Time
	ConfirmedAt   *time.Time
	LastUsedAt    time.Time
}

type User struct {
	ID           uuid.UUID
	Login        string
	DisplayName  string
	PasswordHash string
	IsAdmin      bool
	CreatedAt    time.Time
	AvatarSha256 []byte
}
