/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка работоспособности */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация по инвайту
         * @description Создаёт пользователя и сразу открывает сессию. Инвайт одноразовый.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход
         * @description Закрывает текущую сессию и удаляет cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сменить логин
         * @description Нужен текущий пароль. Сессии не завершаются. Неверный пароль — `403`, не `401`: сессия действительна.
         *     Неудачные попытки считаются вместе с попытками входа.
         */
        put: operations["changeLogin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сменить пароль
         * @description Нужен текущий пароль. Все сессии, кроме текущей, завершаются.
         *     Неверный пароль — `403`, не `401`: сессия действительна. Неудачные попытки считаются вместе с попытками входа.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список инвайтов
         * @description Только для администратора. Коды не возвращаются — сервер хранит лишь их хеши.
         */
        get: operations["listInvites"];
        put?: never;
        /**
         * Создать инвайт
         * @description Только для администратора. Код возвращается один раз — в этом ответе.
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активные сессии текущего пользователя */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        /** Выйти на всех остальных устройствах */
        delete: operations["deleteOtherSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Завершить сессию
         * @description Своя сессия; текущая — то же, что выход.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Отозвать инвайт
         * @description Только для администратора и только неиспользованный инвайт.
         */
        delete: operations["deleteInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            /**
             * @description Версия сборки сервера; "dev" — собран без -ldflags.
             * @example 0.1.0
             */
            version: string;
        };
        /** @description Уникален без учёта регистра. */
        Login: string;
        Password: string;
        User: {
            /** Format: uuid */
            id: string;
            login: components["schemas"]["Login"];
            displayName: string;
            isAdmin: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        SessionInfo: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description Вход.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description С точностью до часа.
             */
            lastUsedAt: string;
            userAgent: string;
            /** @description Сессия этого запроса. */
            current: boolean;
        };
        Invite: {
            /** Format: uuid */
            id: string;
            /** @description Только в ответе на создание. */
            code?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /**
             * Format: date-time
             * @description Нет поля — инвайт не использован.
             */
            usedAt?: string;
            /** @description Логин зарегистрировавшегося (нет поля, если пользователь удалён). */
            usedBy?: string;
        };
        Error: {
            /**
             * @description Описание ошибки для человека.
             * @example Not Found
             */
            error: string;
            /**
             * @description Машиночитаемый код. Общие: `bad_request`, `too_large`, `unsupported_media_type`, `unauthorized`,
             *     `session_revoked`, `forbidden`, `not_found`, `method_not_allowed`, `rate_limited`,
             *     `too_many_attempts`, `internal`;
             *     остальные — в описаниях ответов конкретных операций.
             * @example not_found
             */
            code: string;
        };
    };
    responses: {
        /** @description Ошибка. Для 405 — заголовок Allow. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `too_many_attempts` — слишком много неудачных попыток с этого адреса или для этого логина. */
        TooManyAttempts: {
            headers: {
                /** @description Через сколько секунд можно повторить. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Сессия открыта; токен также установлен в cookie `session`. */
        Session: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    token: string;
                    user: components["schemas"]["User"];
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервер работает. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Код инвайта; регистр и пробелы по краям не важны. */
                    invite: string;
                    login: components["schemas"]["Login"];
                    password: components["schemas"]["Password"];
                    /** @description Отображаемое имя; по умолчанию — логин. */
                    displayName?: string;
                };
            };
        };
        responses: {
            201: components["responses"]["Session"];
            /** @description `invalid_invite`, `invalid_login`, `invalid_password`, `invalid_display_name`, `bad_request`. */
            400: components["responses"]["Error"];
            /** @description `login_taken`. Инвайт при этом не расходуется. */
            409: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Без учёта регистра. */
                    login: string;
                    password: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Session"];
            /** @description `invalid_credentials` — неверный логин или пароль (что именно — не уточняется). */
            401: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия закрыта. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь текущей сессии. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    changeLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login: components["schemas"]["Login"];
                    /** @description Текущий пароль. */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Логин изменён (или совпадал с текущим). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description `invalid_login`. */
            400: components["responses"]["Error"];
            /** @description `wrong_password` — неверный текущий пароль. */
            403: components["responses"]["Error"];
            /** @description `login_taken`. */
            409: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: components["schemas"]["Password"];
                };
            };
        };
        responses: {
            /** @description Пароль изменён, остальные сессии завершены. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_password` — новый пароль не подходит по длине. */
            400: components["responses"]["Error"];
            /** @description `wrong_password` — неверный текущий пароль. */
            403: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Инвайты, новые первыми. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"][];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 7 */
                    expiresInDays?: number;
                };
            };
        };
        responses: {
            /** @description Инвайт создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"] & unknown;
                };
            };
            /** @description `invalid_expiry`. */
            400: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессии, последние использованные первыми. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    deleteOtherSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все сессии, кроме текущей, завершены. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Error"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия завершена. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found`. */
            404: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    deleteInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Инвайт удалён. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found` — нет такого или уже использован. */
            404: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
}
