/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Проверка работоспособности */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Регистрация по инвайту
         * @description Создаёт пользователя и сразу открывает сессию. Инвайт одноразовый.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Вход */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход
         * @description Закрывает текущую сессию и удаляет cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Текущий пользователь */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сменить логин
         * @description Нужен текущий пароль. Сессии не завершаются. Неверный пароль — `403`, не `401`: сессия действительна.
         *     Неудачные попытки считаются вместе с попытками входа.
         */
        put: operations["changeLogin"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Сменить пароль
         * @description Нужен текущий пароль. Все сессии, кроме текущей, завершаются.
         *     Неверный пароль — `403`, не `401`: сессия действительна. Неудачные попытки считаются вместе с попытками входа.
         */
        put: operations["changePassword"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Поставить аватар
         * @description Тело — сама картинка (PNG, JPEG или WebP, до 5 МБ и 8000 px по стороне). Сервер вырезает квадрат
         *     из середины, уменьшает до 256 px и сохраняет заново в JPEG (без метаданных). Прежний аватар
         *     удаляется автоматически, если на него больше ничто не ссылается.
         */
        put: operations["setAvatar"];
        post?: never;
        /** Убрать аватар */
        delete: operations["removeAvatar"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blobs/{sha256}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Картинка по хешу
         * @description Аватары (и позже портреты) — по SHA-256 содержимого. Содержимое под хешем не меняется:
         *     `Cache-Control: private, max-age=31536000, immutable`, `ETag` — хеш в кавычках.
         */
        get: operations["getBlob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Список инвайтов
         * @description Только для администратора. Коды не возвращаются — сервер хранит лишь их хеши.
         */
        get: operations["listInvites"];
        put?: never;
        /**
         * Создать инвайт
         * @description Только для администратора. Код возвращается один раз — в этом ответе.
         */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Активные сессии текущего пользователя */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        /** Выйти на всех остальных устройствах */
        delete: operations["deleteOtherSessions"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Завершить сессию
         * @description Своя сессия; текущая — то же, что выход.
         */
        delete: operations["deleteSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Отозвать инвайт
         * @description Только для администратора и только неиспользованный инвайт.
         */
        delete: operations["deleteInvite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Изменения своих анкет
         * @description Анкеты текущего пользователя, изменённые после курсора `since`, по порядку изменений.
         *     Без `since` (или 0) — все живые анкеты, без надгробий. Ответ даёт новый курсор — его передать
         *     в следующий раз. Курсор новее известного серверу (база пересоздана) — ответ как без `since`.
         */
        get: operations["listCharacterChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Анкета
         * @description Своя анкета, в том числе надгробие. `ETag` — ревизия.
         */
        get: operations["getCharacter"];
        /**
         * Создать или изменить анкету
         * @description Тело — файл анкеты (`character.schema.json`); `id` в нём — как в пути. Лист сервер не проверяет.
         *     Нужен ровно один заголовок условия: `If-None-Match: *` — создать, `If-Match: "<ревизия>"` — изменить
         *     версию с этой ревизией (в том числе вернуть удалённую). Надгробие можно перезаписать так же.
         */
        put: operations["putCharacter"];
        post?: never;
        /**
         * Удалить анкету
         * @description Оставляет надгробие — удаление дойдёт до других устройств. Удалённую — 200 без изменений.
         */
        delete: operations["deleteCharacter"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @constant */
            status: "ok";
            /**
             * @description Версия сборки сервера; "dev" — собран без -ldflags.
             * @example 0.1.0
             */
            version: string;
        };
        /** @description Уникален без учёта регистра. */
        Login: string;
        Password: string;
        /** @description SHA-256 в hex, строчными. */
        Sha256: string;
        User: {
            /** @description Аватар — GET /api/blobs/{sha256}; null — нет. */
            avatar: components["schemas"]["Sha256"] | null;
            /** Format: uuid */
            id: string;
            login: components["schemas"]["Login"];
            displayName: string;
            isAdmin: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        SessionInfo: {
            /** Format: uuid */
            id: string;
            /**
             * Format: date-time
             * @description Вход.
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description С точностью до часа.
             */
            lastUsedAt: string;
            userAgent: string;
            /** @description Сессия этого запроса. */
            current: boolean;
        };
        Invite: {
            /** Format: uuid */
            id: string;
            /** @description Только в ответе на создание. */
            code?: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
            /**
             * Format: date-time
             * @description Нет поля — инвайт не использован.
             */
            usedAt?: string;
            /** @description Логин зарегистрировавшегося (нет поля, если пользователь удалён). */
            usedBy?: string;
        };
        StoredCharacter: {
            /** Format: uuid */
            id: string;
            /** @description Растёт на 1 с каждой записью; для `If-Match`. */
            revision: number;
            deleted: boolean;
            /**
             * Format: date-time
             * @description Время записи на сервере.
             */
            updatedAt: string;
            /** @description Нет у надгробия и в ответе на запись (там клиент и так знает содержимое). */
            character?: components["schemas"]["character.schema"];
        };
        Error: {
            /**
             * @description Описание ошибки для человека.
             * @example Not Found
             */
            error: string;
            /**
             * @description Машиночитаемый код. Общие: `bad_request`, `too_large`, `unsupported_media_type`, `unauthorized`,
             *     `session_revoked`, `forbidden`, `not_found`, `method_not_allowed`, `rate_limited`,
             *     `too_many_attempts`, `internal`;
             *     остальные — в описаниях ответов конкретных операций.
             * @example not_found
             */
            code: string;
        };
        /** @description Стабильный идентификатор записи каталога; на него ссылается лист персонажа. Не меняется между ревизиями пакета. */
        id: string;
        /** @description Значение из каталога контента (id — показывается на языке контента) или своё, введённое игроком (custom — не переводится). */
        choice: {
            id: components["schemas"]["id"];
        } | {
            custom: string;
        };
        characteristic: {
            /** @description Значение при создании; null — не введено. */
            base?: number | null;
            /**
             * @description Шаги улучшения по +5 (0–4; вне диапазона — диагностика, не ошибка формата).
             * @default 0
             */
            advances: number;
            /**
             * @description Множитель бонуса (Unnatural); 1 — обычная характеристика.
             * @default 1
             */
            unnatural: number;
        };
        modifier: {
            /** @description Идентификатор стата, например characteristic.ag. */
            target: string;
            value: number;
            reason?: string;
        };
        skill: {
            /** @description Идентификатор навыка в контенте. */
            skill: components["schemas"]["id"];
            specialization?: components["schemas"]["choice"];
            /**
             * @description 1 — обучен, 2 — +10, 3 — +20 (вне диапазона — диагностика).
             * @default 1
             */
            training: number;
        };
        /**
         * Dark Heresy 1e sheet (sheetVersion 4)
         * @description Лист Dark Heresy 1e. Отсутствующие поля читаются как пустые / по умолчанию. v1: только player, homeworld, career, rank; v2: + characteristics, modifiers; v3: + skills; v4: homeworld, career, rank, skills[].specialization — choice вместо строки (миграция: строка s → {"custom": s}). Старые версии мигрируют с пустыми новыми полями.
         */
        "dh1-sheet.schema": {
            /** @description Устарело: игрок — author в конверте. Читается из старых файлов, клиенты не показывают и не пишут. */
            player?: string;
            homeworld?: components["schemas"]["choice"];
            career?: components["schemas"]["choice"];
            rank?: components["schemas"]["choice"];
            /** @description Ключи: ws, bs, s, t, ag, int, per, wp, fel. Неизвестные ключи игнорируются. */
            characteristics?: {
                [key: string]: components["schemas"]["characteristic"];
            };
            /** @description Временные модификаторы, введённые пользователем. */
            modifiers?: components["schemas"]["modifier"][];
            /** @description Изученные навыки; необученные базовые берутся из каталога контента. */
            skills?: components["schemas"]["skill"][];
            $defs: {
                /** @description Значение из каталога контента (id — показывается на языке контента) или своё, введённое игроком (custom — не переводится). */
                choice: {
                    id: components["schemas"]["id"];
                } | {
                    custom: string;
                };
                characteristic: {
                    /** @description Значение при создании; null — не введено. */
                    base?: number | null;
                    /**
                     * @description Шаги улучшения по +5 (0–4; вне диапазона — диагностика, не ошибка формата).
                     * @default 0
                     */
                    advances: number;
                    /**
                     * @description Множитель бонуса (Unnatural); 1 — обычная характеристика.
                     * @default 1
                     */
                    unnatural: number;
                };
                modifier: {
                    /** @description Идентификатор стата, например characteristic.ag. */
                    target: string;
                    value: number;
                    reason?: string;
                };
                skill: {
                    /** @description Идентификатор навыка в контенте. */
                    skill: components["schemas"]["id"];
                    specialization?: components["schemas"]["choice"];
                    /**
                     * @description 1 — обучен, 2 — +10, 3 — +20 (вне диапазона — диагностика).
                     * @default 1
                     */
                    training: number;
                };
            };
        };
        /**
         * Seydlitz Dataslate character
         * @description Файл персонажа: конверт платформы + лист системы. Один формат для хранилища, экспорта и сервера.
         */
        "character.schema": {
            /** @constant */
            format: "seydlitz.character";
            /** @description Версия конверта. Клиент отклоняет файлы новее, чем понимает. */
            formatVersion: number;
            /** Format: uuid */
            id: string;
            /**
             * @description Идентификатор игровой системы; определяет схему поля sheet.
             * @example dh1
             */
            system: string;
            /** @description Версия формата листа системы. Старые версии модуль системы мигрирует, новее — отклоняет. */
            sheetVersion: number;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** @description Учётка, создавшая анкету. name — имя на момент записи, для показа без сервера */
            author?: {
                /** Format: uuid */
                id: string;
                name: string;
            };
            sheet: Record<string, never>;
        } & unknown;
    };
    responses: {
        /** @description Записано (201 — создано). Без `character`. */
        CharacterWritten: {
            headers: {
                ETag: components["headers"]["Revision"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StoredCharacter"];
            };
        };
        /**
         * @description На сервере другая ревизия (или анкета уже есть при `If-None-Match: *`). Тело — не ошибка,
         *     а версия сервера, с `character`, если не удалена: клиент предлагает выбор.
         */
        CharacterConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["StoredCharacter"];
            };
        };
        /** @description Ошибка. Для 405 — заголовок Allow. */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description `too_many_attempts` — слишком много неудачных попыток с этого адреса или для этого логина. */
        TooManyAttempts: {
            headers: {
                /** @description Через сколько секунд можно повторить. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Сессия открыта; токен также установлен в cookie `session`. */
        Session: {
            headers: {
                "Set-Cookie"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    token: string;
                    user: components["schemas"]["User"];
                };
            };
        };
    };
    parameters: {
        /** @description Ревизия в кавычках, на которой основана правка. */
        IfMatch: string;
    };
    requestBodies: never;
    headers: {
        /** @description Ревизия в кавычках. */
        Revision: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сервер работает. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Код инвайта; регистр и пробелы по краям не важны. */
                    invite: string;
                    login: components["schemas"]["Login"];
                    password: components["schemas"]["Password"];
                    /** @description Отображаемое имя; по умолчанию — логин. */
                    displayName?: string;
                };
            };
        };
        responses: {
            201: components["responses"]["Session"];
            /** @description `invalid_invite`, `invalid_login`, `invalid_password`, `invalid_display_name`, `bad_request`. */
            400: components["responses"]["Error"];
            /** @description `login_taken`. Инвайт при этом не расходуется. */
            409: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description Без учёта регистра. */
                    login: string;
                    password: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Session"];
            /** @description `invalid_credentials` — неверный логин или пароль (что именно — не уточняется). */
            401: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия закрыта. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Пользователь текущей сессии. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    changeLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    login: components["schemas"]["Login"];
                    /** @description Текущий пароль. */
                    password: string;
                };
            };
        };
        responses: {
            /** @description Логин изменён (или совпадал с текущим). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description `invalid_login`. */
            400: components["responses"]["Error"];
            /** @description `wrong_password` — неверный текущий пароль. */
            403: components["responses"]["Error"];
            /** @description `login_taken`. */
            409: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    currentPassword: string;
                    newPassword: components["schemas"]["Password"];
                };
            };
        };
        responses: {
            /** @description Пароль изменён, остальные сессии завершены. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `invalid_password` — новый пароль не подходит по длине. */
            400: components["responses"]["Error"];
            /** @description `wrong_password` — неверный текущий пароль. */
            403: components["responses"]["Error"];
            429: components["responses"]["TooManyAttempts"];
            "4XX": components["responses"]["Error"];
        };
    };
    setAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/png": unknown;
                "image/jpeg": unknown;
                "image/webp": unknown;
            };
        };
        responses: {
            /** @description Аватар изменён. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description `invalid_image` — не PNG, JPEG или WebP либо файл повреждён. */
            400: components["responses"]["Error"];
            /** @description `too_large` — больше 5 МБ или 8000 px по стороне. */
            413: components["responses"]["Error"];
            /** @description `unsupported_media_type` — Content-Type не image/png, image/jpeg или image/webp. */
            415: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    removeAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Аватар убран. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    getBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sha256: components["schemas"]["Sha256"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Картинка. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Не изменилась (`If-None-Match`). */
            304: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found`. */
            404: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    listInvites: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Инвайты, новые первыми. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"][];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @default 7 */
                    expiresInDays?: number;
                };
            };
        };
        responses: {
            /** @description Инвайт создан. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"] & unknown;
                };
            };
            /** @description `invalid_expiry`. */
            400: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессии, последние использованные первыми. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"][];
                };
            };
            "4XX": components["responses"]["Error"];
        };
    };
    deleteOtherSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Все сессии, кроме текущей, завершены. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            "4XX": components["responses"]["Error"];
        };
    };
    deleteSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Сессия завершена. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found`. */
            404: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    deleteInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Инвайт удалён. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description `not_found` — нет такого или уже использован. */
            404: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    listCharacterChanges: {
        parameters: {
            query?: {
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Изменения. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        cursor: number;
                        changes: components["schemas"]["StoredCharacter"][];
                    };
                };
            };
            /** @description `bad_request` — `since` не число. */
            400: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    getCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Анкета. */
            200: {
                headers: {
                    ETag: components["headers"]["Revision"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredCharacter"];
                };
            };
            /** @description `not_found`. */
            404: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    putCharacter: {
        parameters: {
            query?: never;
            header?: {
                /** @description Ревизия в кавычках, на которой основана правка. */
                "If-Match"?: components["parameters"]["IfMatch"];
                "If-None-Match"?: "*";
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["character.schema"];
            };
        };
        responses: {
            200: components["responses"]["CharacterWritten"];
            201: components["responses"]["CharacterWritten"];
            /** @description `invalid_character` — не файл анкеты или `id` не как в пути. */
            400: components["responses"]["Error"];
            /** @description `not_found` — `If-Match`, а анкеты на сервере нет: создать заново через `If-None-Match: *`. */
            404: components["responses"]["Error"];
            /** @description `id_taken` — анкета с этим id есть у другого пользователя; сохранить под новым id. */
            409: components["responses"]["Error"];
            412: components["responses"]["CharacterConflict"];
            /** @description `too_large` — больше 256 КБ. */
            413: components["responses"]["Error"];
            /** @description `precondition_required` — нет `If-Match` или `If-None-Match: *`. */
            428: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
    deleteCharacter: {
        parameters: {
            query?: never;
            header?: {
                /** @description Ревизия в кавычках, на которой основана правка. */
                "If-Match"?: components["parameters"]["IfMatch"];
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["CharacterWritten"];
            /** @description `not_found`. */
            404: components["responses"]["Error"];
            /** @description `id_taken` — анкета другого пользователя. */
            409: components["responses"]["Error"];
            412: components["responses"]["CharacterConflict"];
            /** @description `precondition_required` — нет `If-Match`. */
            428: components["responses"]["Error"];
            "4XX": components["responses"]["Error"];
        };
    };
}
